baseURL = 'https://example.org/'
languageCode = 'da'
title = 'Siv & Oliver'
theme = 'ananke'

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "Vi skal giftes – læs alt du behøver at vide her"
  featured_image = "/images/hero.jpg"
  cover_dimming_class = "bg-black-40"
  background_color_class = "bg-orange"
  body_classes = "avenir bg-near-white"

[params.ananke]
  show_recent_posts = false

[params.ananke.home]
  content_alignment = "center"

[[menus.main]]
  name = "Program"
  url = "/schedule/"
  weight = 1

[[menus.main]]
  name = "Praktisk info"
  url = "/venue/"
  weight = 2

[[menus.main]]
  name = "Ønskeliste"
  url = "/gift-registry/"
  weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'